# [theme]
# base="light"
# primaryColor =
# backgroundColor =
# secondaryBackgroundColor =
# textColor =
# font =

[client]
# toolbarMode = "auto"
showErrorDetails = true
showSidebarNavigation = true

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

# [browser]
# serverAddress = "localhost"
# gatherUsageStats = false

[runner]
fastReruns = true

