[theme]
base="light"
# primaryColor =
# backgroundColor =
# secondaryBackgroundColor =
# textColor =
# font =

[client]
# toolbarMode = "auto"
showSidebarNavigation = true

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200